### ISSUE TITLE
Netflix: Language selection list does not open

### ISSUE THREAD

**Issue by Nitrino** [Nitrino/easysubs#141]

**Comment by enzet** [comment]
Same problem. macOS Catalina 10.15, Google Chrome 85.0.

(But there is always a keyboard: tab + arrows).

**Comment by Ilya-Lad** [comment]
It's a pity that the bug persists. It may not be felt in say Russia and other countries, where the browser system's language ( that is window.navigator.language ) and the language the people would  want to translate to, are commonly the same.

But in my huge town of Toronto, for example,  60%  of the population are the immigrants speaking  dozens of native languages, including myself.  We typically have our browser language set to  English, but we want the translation language to be our native one. Which is not easy to set.

So the immigrant public of big American and European cities may unnecessarily leave, without bothering to discover the above mentioned  method by eznet.

I believe there exists another basic reason why extensions like Eayssubs or Lanaguage Learning for Netflix /  You Tube are more popular among, say, diligent learners of exotic languages, rather than among the immigrants. ( I am only guessing that what I am saying is true, having no statistics). The immigrants (and a great many of the Globe's  advanced English learners) know the vocabulary of the main second languages well enough. They would not save many words or bother with the Puzzle English service. Their main problem with feature movies in L2 is listening comprehension.  Plus some infrequent help with the vocabulary and the movie idioms and slang. Their need is just watch the movie in L2, after work, enjoy it, and understand it better, and go to bed in the believe that their L2 has improved. Which will indeed improve, if one comes through the meaningful content through a lot of listening, quoting Steve Kauffmann, the Canadian polyglot and the founder of Lingq. ( Though Ling'q main functions, ironically, helped more with the saving and reviewing of new words rather than with helping users to understand fluent speech).

Petr, I like you extension and your code very much. The extension is potentially better than many other, in my opinion. Thank for making the code  open source. What are your plans, if any,  for its  development?

Ya tozhe zhil kogda-to v Moskve i lublu govorit' po russki!

Ilya

**Comment by Nitrino** [comment]
@Ilya-Lad I have already been able to reproduce this bug and it will be fixed in the next version.
Thanks for your feedback, it is very inspiring to develop the extension.

I have outlined my immediate plans in this comment 
https://github.com/Nitrino/easysubs/issues/148#issuecomment-712464252 

In the long-term plans, everything that is currently in the issues.
I would like to further focus on text analysis and better translate phrases and idioms.
If you have any suggestions for development, I will gladly listen to them.

> Ya tozhe zhil kogda-to v Moskve i lublu govorit' po russki!
Приятно познакомиться!

**Comment by Ilya-Lad** [comment]
Очень приятно, Петр!
И спасибо Вам за ответы на мои вопросы.

I really have suggestions, and would be glad to discuss them with you. I will soon email to nitrinodev@gmail.com to agree on the time and maybe the agenda. Will Skype talk be ok?

**Comment by Ilya-Lad** [comment]
@Nitrino. Thanks for the new release and the fixed bugs.
My email penetrated you like neutrino.
