### ISSUE TITLE
make text white and easy to read 

### ISSUE THREAD

**Issue by hichemqq** [Nitrino/easysubs#151]
![image](https://user-images.githubusercontent.com/53800495/81490136-33bc5c00-9276-11ea-9fdb-44db1e5e75a8.png)
hello as you can see, the text is dark, can you please make it more white or increase the opacity of background so it appear clearly? thank you so much

**Comment by xamgore** [comment]
Same here. Youtube subtitles have a clear white color.

![image](https://user-images.githubusercontent.com/4586392/82130352-54833500-97d3-11ea-8e7f-1f698d80ffeb.png)

Setting `z-index` to 22 solves the issue.

![image](https://user-images.githubusercontent.com/4586392/82130471-4681e400-97d4-11ea-94b3-85691ed8d7ab.png)

**Comment by Nitrino** [comment]
Hi guys. Thanks for the feedback. 
@xamgore  you're completely right, z-index should fix this bug. 
Regarding the large z-index values, I try not to put them huge, so that later I could overlap it. Usually, I just increase them in increments of 10 so that I can add intermediate values.

I will be happy to pull requests

**Comment by hichemqq** [comment]
thanks you're amazing <3

**Comment by Nitrino** [comment]
Fixed in #154
