### ISSUE TITLE
`index.CUsFxaJS.js:8 Uncaught (in promise) Error: Not Implimented streaming service`

### ISSUE THREAD

**Issue by rakleed** [Nitrino/easysubs#249]
When opening any website, the following error appears in the developer console:
```log
index.CUsFxaJS.js:8 Uncaught (in promise) Error: Not Implimented streaming service
    at Hn.init (index.CUsFxaJS.js:8:190)
    at main.CAf-gccy.js:211:374526
    at Object.watch (index.CUsFxaJS.js:1:5682)
    at main.CAf-gccy.js:211:374033
```

However, if you disable your extension, the error will no longer appear.

**Comment by Nitrino** [comment]
Hi @rakleed. Thanks for the feedback.
It's strange that this happens, since the extension can only work with a specific list of domains. I'll try to repeat it and figure out what's wrong. Can you add details:
- your browser
- extension version (you can see it in the list of extensions)
- Is the extension installed from the store or from source?
- Any other details that would help me to reproduce this behavior
